### ISSUE TITLE
items don't disappear with just Curious

### ISSUE THREAD

**Issue by mazewhity** [Zandre02/ProjectMCRPG#1]
But can confirm that items don't disappear with just Curious, Botania and Create. And neither they do with Inventory Sorter added. So I guess as an issue, it's not a Curious thing on it's own.

So then I though about what else deals with inventory stuff on the pack and figured out the cause. It's Inventory Essentials. When this is added the item in the head slot does disappear.

PS: With just Inventory Essentials it doesn't happen, it's only when both Inventory Sorter and Inventory Essentials is present.

**Comment by mazewhity** [comment]
https://github.com/TheIllusiveC4/Curios/issues/391

**Comment by Zandre02** [comment]
inventorySorter by cpw is causing compatibility issues when used in conjunction with inventory essentials, curios, create, inventory stacking and sophisticated backpacks
Many issues around inventorySorter causing item disapearances with various mod combinations

Solution: Remove inventorySorter
